### ISSUE TITLE
Node16 deprecation

### ISSUE THREAD

**Issue by drexhage** [advanced-security/generate-sbom-action#43]
[Node16 is deprecated by Github Actions](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). I think you need to update to "node20" in the actions.yml and bump the octokit version to 3.0.0 or higher. If this action isn't considered maintained, then please leave a comment in the readme.

**Comment by colindembovsky** [comment]
Hi @drexhage I have updated the node version! In future, PRs are welcome.
